version: '3.5'
services:
  web:
    image: nginx:1.16
    ports:
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/cache/:/var/cache/nginx/
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
  redis:
    image: redis:6
    ports:
      - 6379:6379
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
